timeout: 25m

options:
  pool:
    name: projects/ci-account/locations/us-west1/workerPools/high-cpu-pool

  # This build needs to run in environments where the _GITHUB_DEPLOY_KEY_SRC
  # substitution is defined, but also environments where it isn't. The
  # ALLOW_LOOSE option disables GCB's strict checking of substitution usage,
  # so that the build will still run if _GITHUB_DEPLOY_KEY_SRC is not defined.
  substitution_option: ALLOW_LOOSE

steps:
  # Run the integration tests. Actual content of this job depends on the changes
  # detected in the PR
  - name: quay.io/gravitational/teleport-buildbox:teleport10
    id: run-tests
    dir: /workspace/.cloudbuild/scripts
    entrypoint: bash
    args:
      - -c
      - |
        go run ./cmd/integration-tests          \
          -target "$_BASE_BRANCH"               \
          -bucket test-logs                     \
          -build "$BUILD_ID"                    \
          -key-secret "$_GITHUB_DEPLOY_KEY_SRC" \
          -a "test-logs/*.json"
    timeout: 25m
